data:
    data_path: "D:/ProjectImages/SyntheticContrast/train"
    down_sample: 1
    patch_size: [64, 64, 64]
    num_examples: 4
    cv_folds: 3
    fold: 2
augmentation:
    use: true
    source_dims: [3, 512, 512]
    target_dims: [12, 512, 512]
    flip_prob: 0.5
    rotation: 45.0
    scale: [0.8, 1.6]
    shear: 15.0
    translate: [0.25, 0.25]
